name: "Generate Daily Report"
description: "Generate a daily activity report using nippo"

inputs:
  date:
    description: "Target date (YYYY-MM-DD). Defaults to today."
    required: false
    default: ""
  github_user:
    description: "GitHub username. Defaults to the actor."
    required: false
    default: ${{ github.actor }}
  gh_token:
    description: "GitHub token with repo scope (for private repo activity)"
    required: true
  output:
    description: "Output directory for reports"
    required: false
    default: "./reports"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: shun0918/nippo
        path: .nippo-tool

    - name: Generate report
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        GITHUB_USER: ${{ inputs.github_user }}
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_DATE: ${{ inputs.date }}
      run: |
        ./.nippo-tool/scripts/generate-report.sh --output "$INPUT_OUTPUT" ${INPUT_DATE:+"$INPUT_DATE"}
